---
abstract: 'Deprecated module to translate PodToHTML'
author:
  - 'Nick Ing-Simmons (maintained by brian d foy <bdfoy@cpan.org>)'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PodToHTML
no_index:
  directory:
    - t
    - inc
requires:
  HTML::AsSubs: '0'
  HTML::Element: '0'
  HTML::Entities: '0'
  HTML::FormatPS: '0'
  Pod::Parser: '0'
version: '0.09'
